### ISSUE TITLE
bug: warp errors out after succesful aretomo runs

### ISSUE THREAD

**Issue by jmdobbs** [warpem/warp#40] opened 2024-04-30 16:43 UTC
Hi,
From the testing @ThomasHoffmann77 and I have been doing, it appears that warp doesn't properly recognize successful aretomo jobs, or somehow can't recover from running the job. After aretomo finishes running (and the files are written to the tiltstack directory), we get the error

2024-04-30 08:00:25.140 System.InvalidOperationException: Cannot mix synchronous and asynchronous operation on process stream.
2024-04-30 08:00:25.140    at System.Diagnostics.Process.get_StandardOutput()
2024-04-30 08:00:25.140    at WarpWorker.WarpWorker.EvaluateCommand(NamedSerializableObject Command)

See attached for job log
[gTS_003.log](https://github.com/warpem/warp/files/15168168/gTS_003.log)

**Comment by alisterburt** [comment] 2024-04-30 17:46
This one looks like a real bug, I'm not sure why you're running into it when we're not - @dtegunov  could this be caused by the recent  changes you made to logging?

**Comment by dtegunov** [comment] 2024-05-01 04:34
Correct, fixed in fc22b43f5cd826a0760a1d95dc174ab67804d93b

**Closed** 2024-05-01 04:34 UTC
